name: Deploy pythonanywhere webapp
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Upload files
      # ...

      - name: Reload webapp
        uses: jensvog/pythonanywhere-webapp-reload-action@v1
        with:
          host: 'eu.pythonanywhere.com'
          username: 'scharlau'
          api-token: '73b8454c48b927b26df9e1f7331fc2d627880f78'
          domain-name: 'scharlau.pythonanywhere.com'
